# Generated by Django 3.2.4 on 2021-06-19 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('birthdate', models.DateField()),
                ('school', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='pictures/sources')),
                ('result_image', models.ImageField(blank=True, upload_to='pictures/results')),
                ('result_image_string', models.TextField(blank=True)),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.user', to_field='email')),
            ],
        ),
    ]
